#!/bin/bash

if [[ $# -lt 2 ]]; then
    echo "Usage $0 <year> <day>"
    exit 1
fi

year=$1
day=$2

path="./$year/day${day}/sol.py"

if [[ ! -f "./$year/day${day}/sol.py" ]]; then
    echo "File '$path' does not exist!"
    exit 1
fi

python3 -m "${year}.day${day}.sol"
